-- ============================================
-- Studenten database - 100 voorbeeldstudenten
-- ============================================

CREATE DATABASE IF NOT EXISTS mydatabase;
USE mydatabase;

DROP TABLE IF EXISTS studenten;

CREATE TABLE studenten (
    id INT AUTO_INCREMENT PRIMARY KEY,
    voornaam VARCHAR(50) NOT NULL,
    achternaam VARCHAR(50) NOT NULL,
    leeftijd INT NOT NULL,
    woonplaats VARCHAR(100) NOT NULL,
    klas VARCHAR(5) NOT NULL,
    gender VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO studenten (voornaam, achternaam, leeftijd, woonplaats, klas, gender, email) VALUES
('Liam', 'de Vries', 16, 'Amsterdam', '1A', 'Man', 'liam.de.vries@school.nl'),
('Sofia', 'Jansen', 15, 'Rotterdam', '1A', 'Vrouw', 'sofia.jansen@school.nl'),
('Noah', 'van den Berg', 17, 'Utrecht', '1B', 'Man', 'noah.van.den.berg@school.nl'),
('Amara', 'Bakker', 16, 'Den Haag', '1B', 'Vrouw', 'amara.bakker@school.nl'),
('Finn', 'Visser', 15, 'Eindhoven', '1C', 'Non-binair', 'finn.visser@school.nl'),
('Zara', 'Smit', 16, 'Tilburg', '1C', 'Vrouw', 'zara.smit@school.nl'),
('Jayden', 'Meijer', 17, 'Groningen', '1A', 'Man', 'jayden.meijer@school.nl'),
('Noor', 'de Boer', 15, 'Almere', '1A', 'Vrouw', 'noor.de.boer@school.nl'),
('Ravi', 'Mulder', 16, 'Breda', '1B', 'Man', 'ravi.mulder@school.nl'),
('Lena', 'de Groot', 17, 'Nijmegen', '1B', 'Vrouw', 'lena.de.groot@school.nl'),
('Sven', 'Bos', 15, 'Enschede', '1C', 'Man', 'sven.bos@school.nl'),
('Yasmine', 'Vos', 16, 'Haarlem', '1C', 'Vrouw', 'yasmine.vos@school.nl'),
('Daan', 'Peters', 17, 'Arnhem', '1A', 'Man', 'daan.peters@school.nl'),
('Imani', 'Hendriks', 15, 'Zaanstad', '1A', 'Vrouw', 'imani.hendriks@school.nl'),
('River', 'van Dijk', 16, 'Amersfoort', '1B', 'Non-binair', 'river.van.dijk@school.nl'),
('Fatima', 'Kuijpers', 17, 'Apeldoorn', '1B', 'Vrouw', 'fatima.kuijpers@school.nl'),
('Lukas', 'van der Berg', 15, 'Delft', '1C', 'Man', 'lukas.van.der.berg@school.nl'),
('Soraya', 'Vermeer', 16, 'Leiden', '1C', 'Vrouw', 'soraya.vermeer@school.nl'),
('Milan', 'Jonkers', 17, 'Dordrecht', '1A', 'Man', 'milan.jonkers@school.nl'),
('Blythe', 'Kramer', 15, 'Zoetermeer', '1A', 'Non-binair', 'blythe.kramer@school.nl'),
('Tariq', 'van Leeuwen', 16, 'Maastricht', '1B', 'Man', 'tariq.van.leeuwen@school.nl'),
('Eva', 'Willems', 17, 'Zwolle', '1B', 'Vrouw', 'eva.willems@school.nl'),
('Jesse', 'Jacobs', 15, 'Deventer', '1C', 'Man', 'jesse.jacobs@school.nl'),
('Priya', 'de Leeuw', 16, 'Den Bosch', '1C', 'Vrouw', 'priya.de.leeuw@school.nl'),
('Sam', 'van Beek', 17, 'Alkmaar', '1A', 'Genderfluid', 'sam.van.beek@school.nl'),
('Ines', 'Claes', 15, 'Heerlen', '1A', 'Vrouw', 'ines.claes@school.nl'),
('Hamza', 'Hermans', 16, 'Venlo', '1B', 'Man', 'hamza.hermans@school.nl'),
('Tess', 'van Ommen', 17, 'Westland', '1B', 'Vrouw', 'tess.van.ommen@school.nl'),
('Koen', 'de Ruiter', 15, 'Sittard', '1C', 'Man', 'koen.de.ruiter@school.nl'),
('Anaya', 'Brouwers', 16, 'Hilversum', '1C', 'Vrouw', 'anaya.brouwers@school.nl'),
('Mats', 'Dekker', 17, 'Emmen', '1A', 'Man', 'mats.dekker@school.nl'),
('Yuki', 'Bosman', 15, 'Helmond', '1A', 'Vrouw', 'yuki.bosman@school.nl'),
('Alex', 'Willems', 16, 'Roosendaal', '1B', 'Non-binair', 'alex.willems@school.nl'),
('Layla', 'Schouten', 17, 'Purmerend', '1B', 'Vrouw', 'layla.schouten@school.nl'),
('Tobias', 'van Rijn', 15, 'Spijkenisse', '1C', 'Man', 'tobias.van.rijn@school.nl'),
('Chiara', 'Smeets', 16, 'Leeuwarden', '1C', 'Vrouw', 'chiara.smeets@school.nl'),
('Omar', 'Berger', 17, 'Ede', '1A', 'Man', 'omar.berger@school.nl'),
('Fenna', 'Martens', 15, 'Hardenberg', '1A', 'Vrouw', 'fenna.martens@school.nl'),
('Sky', 'de Jong', 16, 'Veenendaal', '1B', 'Genderfluid', 'sky.de.jong@school.nl'),
('Aylin', 'Hoekstra', 17, 'Gouda', '1B', 'Vrouw', 'aylin.hoekstra@school.nl'),
('Lucas', 'van der Laan', 15, 'Alphen aan den Rijn', '1C', 'Man', 'lucas.van.der.laan@school.nl'),
('Nadia', 'Huisman', 16, 'Capelle aan den IJssel', '1C', 'Vrouw', 'nadia.huisman@school.nl'),
('Thijs', 'Vink', 17, 'Vlaardingen', '1A', 'Man', 'thijs.vink@school.nl'),
('Rania', 'de Waal', 15, 'Schiedam', '1A', 'Vrouw', 'rania.de.waal@school.nl'),
('Cas', 'van Vliet', 16, 'Nieuwegein', '1B', 'Non-binair', 'cas.van.vliet@school.nl'),
('Naomi', 'Baas', 17, 'Amersfoort', '1B', 'Vrouw', 'naomi.baas@school.nl'),
('Elias', 'Groen', 15, 'Hoorn', '1C', 'Man', 'elias.groen@school.nl'),
('Xena', 'Timmermans', 16, 'Bergen op Zoom', '1C', 'Vrouw', 'xena.timmermans@school.nl'),
('Bram', 'van der Meer', 17, 'Oss', '1A', 'Man', 'bram.van.der.meer@school.nl'),
('Selin', 'Geerts', 15, 'Weert', '1A', 'Vrouw', 'selin.geerts@school.nl'),
('Nino', 'van Dongen', 16, 'Middelburg', '1B', 'Man', 'nino.van.dongen@school.nl'),
('Fleur', 'Puts', 17, 'Venray', '1B', 'Vrouw', 'fleur.puts@school.nl'),
('Zion', 'Cuypers', 15, 'Roosendaal', '1C', 'Non-binair', 'zion.cuypers@school.nl'),
('Amber', 'van Santen', 16, 'Dordrecht', '1C', 'Vrouw', 'amber.van.santen@school.nl'),
('Pieter', 'Aarts', 17, 'Tilburg', '1A', 'Man', 'pieter.aarts@school.nl'),
('Hana', 'Linders', 15, 'Enschede', '1A', 'Vrouw', 'hana.linders@school.nl'),
('Quentin', 'Peeters', 16, 'Arnhem', '1B', 'Man', 'quentin.peeters@school.nl'),
('Zoe', 'Bongers', 17, 'Nijmegen', '1B', 'Vrouw', 'zoe.bongers@school.nl'),
('Erin', 'van Veen', 15, 'Utrecht', '1C', 'Genderfluid', 'erin.van.veen@school.nl'),
('Mariam', 'de Haas', 16, 'Den Haag', '1C', 'Vrouw', 'mariam.de.haas@school.nl'),
('Viktor', 'Nijs', 17, 'Leiden', '1A', 'Man', 'viktor.nijs@school.nl'),
('Lotte', 'Verheij', 15, 'Delft', '1A', 'Vrouw', 'lotte.verheij@school.nl'),
('Idris', 'van Pelt', 16, 'Amsterdam', '1B', 'Man', 'idris.van.pelt@school.nl'),
('Vera', 'Boomsma', 17, 'Rotterdam', '1B', 'Vrouw', 'vera.boomsma@school.nl'),
('Robin', 'de Haas', 15, 'Groningen', '1C', 'Non-binair', 'robin.de.haas@school.nl'),
('Ishaan', 'Niessen', 16, 'Breda', '1C', 'Man', 'ishaan.niessen@school.nl'),
('Manon', 'Vriens', 17, 'Eindhoven', '1A', 'Vrouw', 'manon.vriens@school.nl'),
('Sander', 'Heemskerk', 15, 'Maastricht', '1A', 'Man', 'sander.heemskerk@school.nl'),
('Aiyana', 'van der Wal', 16, 'Zwolle', '1B', 'Vrouw', 'aiyana.van.der.wal@school.nl'),
('Ruben', 'Post', 17, 'Deventer', '1B', 'Man', 'ruben.post@school.nl'),
('Quinn', 'Joosten', 15, 'Den Bosch', '1C', 'Non-binair', 'quinn.joosten@school.nl'),
('Daniyar', 'Koster', 16, 'Alkmaar', '1C', 'Man', 'daniyar.koster@school.nl'),
('Mila', 'Winters', 17, 'Haarlem', '1A', 'Vrouw', 'mila.winters@school.nl'),
('Floris', 'Kusters', 15, 'Zaanstad', '1A', 'Man', 'floris.kusters@school.nl'),
('Roxana', 'Lemmens', 16, 'Heerlen', '1B', 'Vrouw', 'roxana.lemmens@school.nl'),
('Ato', 'van den Brink', 17, 'Venlo', '1B', 'Man', 'ato.van.den.brink@school.nl'),
('Liselotte', 'Arts', 15, 'Hilversum', '1C', 'Vrouw', 'liselotte.arts@school.nl'),
('Emre', 'van Hal', 16, 'Emmen', '1C', 'Man', 'emre.van.hal@school.nl'),
('Nadine', 'Stam', 17, 'Helmond', '1A', 'Vrouw', 'nadine.stam@school.nl'),
('Wout', 'de Vos', 15, 'Spijkenisse', '1A', 'Man', 'wout.de.vos@school.nl'),
('Juno', 'Adriaans', 16, 'Purmerend', '1B', 'Genderfluid', 'juno.adriaans@school.nl'),
('Merel', 'van Gils', 17, 'Leeuwarden', '1B', 'Vrouw', 'merel.van.gils@school.nl'),
('Issa', 'Broers', 15, 'Veenendaal', '1C', 'Man', 'issa.broers@school.nl'),
('Hailey', 'van den Heuvel', 16, 'Gouda', '1C', 'Vrouw', 'hailey.van.den.heuvel@school.nl'),
('Sebastiaan', 'Franke', 17, 'Amersfoort', '1A', 'Man', 'sebastiaan.franke@school.nl'),
('Aicha', 'Wijnands', 15, 'Zoetermeer', '1A', 'Vrouw', 'aicha.wijnands@school.nl'),
('Lex', 'Pronk', 16, 'Apeldoorn', '1B', 'Non-binair', 'lex.pronk@school.nl'),
('Eline', 'van Staveren', 17, 'Ede', '1B', 'Vrouw', 'eline.van.staveren@school.nl'),
('Stef', 'Claassen', 15, 'Middelburg', '1C', 'Man', 'stef.claassen@school.nl'),
('Diarra', 'Otten', 16, 'Weert', '1C', 'Vrouw', 'diarra.otten@school.nl'),
('Hugo', 'Lindeman', 17, 'Hardenberg', '1A', 'Man', 'hugo.lindeman@school.nl'),
('Simone', 'van Zanten', 15, 'Bergen op Zoom', '1A', 'Vrouw', 'simone.van.zanten@school.nl'),
('Kieran', 'de Bruijn', 16, 'Vlaardingen', '1B', 'Man', 'kieran.de.bruijn@school.nl'),
('Fatoumata', 'Wolters', 17, 'Schiedam', '1B', 'Vrouw', 'fatoumata.wolters@school.nl'),
('Bo', 'Hopmans', 15, 'Oss', '1C', 'Non-binair', 'bo.hopmans@school.nl'),
('Yara', 'van Soest', 16, 'Capelle aan den IJssel', '1C', 'Vrouw', 'yara.van.soest@school.nl'),
('Timo', 'Janssen', 17, 'Nieuwegein', '1A', 'Man', 'timo.janssen@school.nl'),
('Esra', 'van Kampen', 15, 'Alphen aan den Rijn', '1A', 'Vrouw', 'esra.van.kampen@school.nl');

-- Overzicht
-- SELECT klas, COUNT(*) AS aantal FROM studenten GROUP BY klas ORDER BY klas;
-- SELECT gender, COUNT(*) AS aantal FROM studenten GROUP BY gender ORDER BY aantal DESC;

